woowacourse-teams/2025-moaon

- .github/workflows/auto-review-assign-pr.yml
close #10 
- 포크한 레포에서 PR을 올리면 Github 정책 상 리뷰어, 라벨 등의 설정을 자동화할 수 없어 403 에러가 발생
- 포크한 레포에서 PR을 올린 경우에는 워크플로우가 실행되지 않게 조건문 추가
> refactor: PR 설정 자동화 워크플로우 수정

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/webpack.config.js
close #9
ts-loader의 fork-ts-checker-webpack-plugin 플러그인 설치한 후 설정을 추가했습니다!
> feat: fork-ts-checker-webpack-plugin 플러그인 설치 및 설정 추가

- frontend/buildspec.yml
- frontend/public/index.html
- frontend/src/App.tsx
- frontend/webpack.config.js
- codebuild 명령어 파일 추가
- FE 프로덕션 배포는 main 브랜치를 타겟으로 하기 때문에 현재 PR에서는 close 이슈하지 않고 main 브랜치 타겟으로 PR 올릴 때 이슈 연결하도록 하겠습니다:)
- 슬랙에 올린 것처럼 아직 람다 함수로 CloudFront 캐시 지우는 부분이 해결 안되어있는데 다른 방식이 있는지 찾아보고 안되면 기술 검토 채널에 권한 관련 문의 드리도록 하겠습니다~!
> chore: codebuild 명령어 파일 추가

- frontend/src/App.tsx
- frontend/src/pages/detail/DetailPage.tsx
- frontend/src/pages/detail/components/carousel/Carousel.styled.ts
- frontend/src/pages/detail/components/carousel/Carousel.tsx
- frontend/src/pages/detail/components/carousel/hooks/useArrowKey.ts
- frontend/src/pages/detail/components/carousel/hooks/useSlide.ts
- frontend/src/shared/components/Layout/GlobalLayout.styled.ts
- frontend/src/shared/components/Layout/GlobalLayout.tsx
- frontend/src/styles/reset.styled.ts
> feat: 캐러셀 컴포넌트 구현

- README.md
연관 이슈가 없습니다.
- 2차 데모데이 때 개발 환경 구축과 CI/CD를 설명할 자료 만들 겸 다이어그램 추가했습니다.
- 메인 리드미에 넣어둘 거라 전체 리뷰어로 추가했어요~
- 보고 마음에 안드는 것 있으면 말해주세요 👍 
프리뷰입니다 😄
> docs(BE): READEM.md 내용 추가

- frontend/src/domains/filter/platform.ts
- frontend/src/domains/filter/techStack.ts
close #65 
기술스택과 플랫폼 아이콘의 이미지 경로를 S3에 저장한 이미지 경로로 변경한다.
> chore(FE): 기술스택, 플랫폼 아이콘 S3 경로 적용

- frontend/src/apis/HttpClient.ts
> fix(FE): Request URL 미입력 문제 해결

- frontend/src/apis/HttpClient.ts
- frontend/webpack.config.js
> fix(FE): proxy 서버 설정 제거

- backend/src/main/java/moaon/backend/global/config/WebConfig.java
- close #72 
- cors 에러 해결을 위한 config 추가
> fix(BE): CORS 에러 해결

- frontend/webpack.config.js
close #76 
- vercel의 환경변수 사용을 위한 systemvars 설정 추가
> fix(FE): 시스템 환경변수 true 설정 추가

- frontend/src/pages/detail/DetailPage.tsx
- frontend/src/pages/detail/components/Post/Post.styled.ts
- frontend/src/pages/detail/components/Post/Post.tsx
- frontend/src/pages/detail/components/Post/styled.ts
- frontend/src/shared/components/Layout/GlobalLayout.styled.ts
close #82 
내일 있을 UT를 대비해서 상세 정보의 트러블 슈팅 섹션을 mock data로 추가했습니다!
@eunoia-jaxson 
콘텐츠가 지정된 높이를 초과할 경우 레이아웃이 깨지는 문제가 발생해, height 속성을 제거하여 유연하게 대응할 수 있도록 조정했습니다.
```tsx
// GlobalLayout.styled.ts
import styled from "@emotion/styled";
export const GlobalLayout = styled.div`
max-width: 80rem;
margin: 2.25rem auto;
height: calc(100dvh - 5.125rem); <= 제거
`;
```
> feat(FE): UT를 위한 상세 정보 Mock Data 추가

- frontend/src/pages/detail/components/Carousel/Carousel.tsx
> fix(FE): 슬라이드가 하나일 때 이전/다음 버튼 숨기기

- backend/compose.yaml
연관 이슈가 없습니다
- 개발 서버에 Nginx를 적용하면서 수정한 내용이 누락되어서 해당 내용 반영합니다.
> fix(BE): CD 오류 수정

- backend/src/main/java/moaon/backend/global/config/WebConfig.java
close #121 
- origin 허용 매핑에 `"https://moaon-preview-*.vercel.app"` 패턴을 추가했습니다.
> feat(FE, BE): preview 배포 주소 origin 허용

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/App.tsx
- frontend/src/libs/googleAnalytics/components/GAInitializer.tsx
- frontend/src/libs/googleAnalytics/constants.ts
- frontend/src/libs/googleAnalytics/hooks/useInitializeGA.ts
- frontend/src/libs/googleAnalytics/hooks/useTrackPageTimeGA.ts
- frontend/src/main.tsx
close #88 
- GA(Google Analytics)를 설치 및 적용
- 페이지에 머무르는 시간을 측정 및 초기값 설정
> feat(FE): GA4 설치 및 적용

- backend/src/main/java/moaon/backend/global/config/WebConfig.java
- close #132 
- 써밋이랑 논의해서 필요없는 도메인 삭제하고, 새로운 도메인 추가했습니다!
- 빠른 Approve 부탁해요~
> refactor(BE): cors allowedOrigins 수정

- frontend/src/domains/filter/techStack.ts
- frontend/src/pages/list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/TechStackSearchResult/TechStackSearchResult.styled.ts
- frontend/src/shared/components/IconBadgeList/IconBadgeList.tsx
close #136 
- 새로운 기술 스택들이 추가되었습니다.(아래 사진 참고)
- S3 버킷에 `teckstack-icons/` 폴더를 만들어 기술 스택 이미지 저장
- 새로 추가된 기술 스택들
> refactor(FE): 기술 스택 상수 데이터 수정

- backend/build.gradle
- backend/compose.yaml
- backend/src/main/java/moaon/backend/global/config/FullTextSearchHQLFunction.java
- backend/src/main/java/moaon/backend/project/repository/CustomizedProjectRepositoryImpl.java
- backend/src/main/resources/META-INF/services/org.hibernate.boot.model.FunctionContributor
- backend/src/test/java/moaon/backend/api/project/ProjectApiTest.java
- backend/src/test/java/moaon/backend/project/repository/CustomizedProjectRepositoryImplTest.java
- backend/src/test/java/moaon/backend/project/repository/MySQLContainerTest.java
- backend/src/test/java/moaon/backend/project/repository/ProjectRepositorySearchTest.java
close #113 
[원본 PR](https://github.com/woowacourse-teams/2025-moaon/pull/135)이 커밋 히스토리가 꼬여서 새로 팠습니다.
> feat(BE): 프로젝트 검색 고도화

- frontend/src/domains/components/SortList/SortList.tsx
- frontend/src/pages/article/ArticleSearchBar/ArticleSearchBar.tsx
- frontend/src/pages/article/TagList/TagList.tsx
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/CategoryFilterBox/CategoryFilterList/CategoryFilterButton/CategoryFilterButton.tsx
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/FilterBox/FilterBox.tsx
- frontend/src/pages/project-list/ProjectSearchBar/ProjectSearchBar.tsx
- frontend/src/pages/project-list/hooks/useFilterParams.ts
- frontend/src/shared/components/Tab/Tab.tsx
- frontend/src/shared/hooks/useSearchParams.ts
close #163 
- 필터 선택 시 `replace: true` 옵션 추가
- 관련 내용 [노션](https://www.notion.so/replace-true-2464b522306480ebbd5fd7e1338d3313?source=copy_link)에 문서화 하였습니다!
> refactor(FE): 필터 선택 시 `replace: true` 옵션 추가

- frontend/src/domains/filter/techStack.ts
close #177 
- 기술 스택 상수 추가(인프라)
> feat(FE): 기술 스택 상수 추가(인프라)

- frontend/src/pages/project-list/FilterContainer/FilterTrigger/FilterBox/FilterBox.styled.ts
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/FilterBox/FilterBox.tsx
close #196 
- 필터 초기화 ui 개선(disabled 추가)
> refactor(FE): 필터 초기화 ui 개선(disabled 추가)

- frontend/src/domains/sort/article.ts
- frontend/src/pages/article/ArticleBox/ArticleBox.styled.ts
- frontend/src/pages/article/ArticleBox/ArticleBox.tsx
- frontend/src/pages/article/TagList/Tag/Tag.styled.ts
- frontend/src/pages/article/TagList/TagList.styled.ts
- frontend/src/pages/project-list/CardList/CardList.styled.ts
- frontend/src/pages/project-list/ProjectListPage.tsx
- frontend/src/shared/components/Tab/Tab.styled.ts
close #204 
- 검색 결과 없을 시 0으로 표시되는 문제 해결
- "23개의 아티클이 모여있어요." 글자 padding 제거
- 태그 글자 크기 조절
> style(FE): 검색 결과 없을 시 0으로 표시되는 문제 해결

- frontend/src/domains/filter/articleCategory.ts
- frontend/src/pages/article/ArticleBox/ArticleSkeletonList/ArticleSkeleton/ArticleSkeleton.styled.ts
- frontend/src/pages/article/ArticleBox/CardList/Card/Card.styled.ts
close #208 
- 아티클 제목, 설명의 높이 값을 지정
- 스켈레톤 높이 값 지정
- 아티클 태그의 색상 수정
> refactor(FE): 아티클 카드 UI 개선

- frontend/src/pages/project-list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/TechStackSearchBar.tsx
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/TechStackSearchResult/TechStackSearchResult.styled.ts
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/TechStackSearchResult/TechStackSearchResult.tsx
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/hooks/useAutoScrollOnFocus.ts
- frontend/src/pages/project-list/FilterContainer/FilterTrigger/TechStackFilterBox/TechStackSearchBar/hooks/useListKeyboardNavigation.ts
close #197 
- 기술 스택 연관 검색어 키보드 접근 로직 추가
- `useListKeyboardNavigation`: 포커스 인덱스 관리, 키보드 위, 아래, 엔터 키 로직 관리
- `useAutoScrollOnFocus`: 포커스 요소 화면에 보이게 스크롤 조정
> feat(FE): 기술 스택 연관 검색어 키보드 접근 로직 추가

- backend/src/main/java/moaon/backend/global/config/CookieConfig.java
- backend/src/main/java/moaon/backend/global/cookie/TrackingCookieManager.java
- backend/src/main/resources/application.yml
> fix(BE) : git 문제 해결

- backend/src/main/java/moaon/backend/article/dto/ArticleContent.java
- backend/src/main/resources/static/docs/index.html
- backend/src/test/java/moaon/backend/api/article/ArticleApiTest.java
- close #261
ArticleContent에 projectTitle 추가
> feat(BE) : ArticleContent에 ProjectTitle 필드 추가

- frontend/src/pages/project-list/FilterContainer/FilterTrigger/FilterBox/FilterBox.styled.ts
close #285 
- 필터 초기화 비활성화 상태 cursor 옵션 수정
> fix(FE): 필터 초기화 비활성화 상태 cursor 옵션 수정

- frontend/src/pages/project-list/CardList/Card/Card.styled.ts
close #301 
- 프로젝트 썸네일 이미지 비율 변경
> refactor(FE): 프로젝트 썸네일 이미지 비율 변경

- frontend/src/domains/filter/articleCategory.ts
- frontend/src/domains/filter/techStack.ts
- frontend/src/pages/article/ArticlePage.tsx
- frontend/src/pages/article/TagList/TagList.tsx
close #300
탭 목록 개선 및 목록에 따른 태그 렌더링
- 전체, FE, BE, Android, iOS, 소프트스킬, 기타 등으로 분리
- 각 탭에 맞는 태그 렌더링
> feat: 탭 목록 개선 및 목록에 따른 태그 렌더링

- frontend/src/shared/components/IconBadgeList/IconBadge/IconBadge.styled.ts
- frontend/src/shared/components/IconBadgeList/IconBadgeList.styled.ts
- frontend/src/shared/components/IconBadgeList/IconBadgeList.tsx
close #303 
- 기본값으로 빈 객체 부여
- 기술 스택 뱃지 UI 수정
- Apple Liquid Glass Mood
> refactor(FE): 프로젝트 상세 페이지 기술 스택 목록 UI 수정 및 기본값 부여

- .github/workflows/prepare-release.yml
- .github/workflows/release.yml
close #282
시멘틱 버저닝을 적용하였습니다.
커밋 내용을 바탕으로 커밋에 fix, feat, feat!와 같은 단어를 읽고 메이저, 마이너, 패치 중 적절한 버전을 자동으로 올릴 수 있게끔 하였습니다.
해당 파일이 develop에 merge된 후, develop에서 main으로 merge를 위한 PR을 생성하는 과정에서 버전을 올리는 커밋이 생성되고 merge가 되면 버전이 올라가는 방식입니다.
> feat: 시멘틱 버저닝 적용

- frontend/package.json
- frontend/src/shared/components/Header/Header.styled.ts
- frontend/src/shared/components/IconBadgeList/IconBadge/IconBadge.styled.ts
close #325 
- 좀비코드 제거
- 헤더 패딩
- 상세 페이지 기술 스택 뱃지 flex-direction
> fix(FE): 스타일 좀비 코드 학살

- frontend/src/App.tsx
- frontend/src/domains/filter/techStack.ts
- frontend/src/shared/components/ScrollToTop/ScrollToTop.tsx
> fix(FE): 크롤링 중 발견한 버그 수정 

- frontend/src/pages/project-detail/components/Carousel/Carousel.styled.ts
- frontend/src/pages/project-detail/components/OverviewSection/OverviewSection.styled.ts
- frontend/src/shared/components/IconBadgeList/IconBadge/IconBadge.styled.ts
close #338
- 상세페이지의 썸네일 배경색상을 검정색에서 흰색으로 변경하였습니다.
- 프로젝트 개요의 영역을 설정하고 단어 단위로 줄바꿈 되도록 하였습니다.
> style(FE): 썸네일 색상 변경

- frontend/public/index.html
- frontend/src/shared/utils/setMetaTags.ts
close #336 
- 크롤러용 메타태그를 index.html 파일에 추가하였습니다.
> refactor(FE): 메타 태그 크롤러용 코드 작성

- backend/src/main/java/moaon/backend/article/domain/Sector.java
- backend/src/main/java/moaon/backend/article/domain/Topic.java
- backend/src/main/java/moaon/backend/global/parser/CursorParser.java
- backend/src/test/java/moaon/backend/global/parser/CursorParserTest.java
- close #417
- ms 초 최대까지 허용하도록 수정했습니다.
> refactor: cursor 형식 수정

- frontend/buildspec.yml
- frontend/package.json
close #425 
빌드 스펙에서 캐시 관련 post_build 단계 제거
> chore(FE): 빌드 스펙에서 캐시 관련 post_build 단계 제거

- .github/workflows/be-prod-cd.yml
- backend/compose.prod.yaml
close #433 
`compose.prod.yaml` 에서 app 컨테이너의 호스트 포트를 80으로 변경합니다.
> chore(BE): 호스트 포트 80번으로 변경
